/**
 * Barra de progresso agregada — exibida no índice de cada seção.
 *
 * Os identificadores dos documentos vêm da barra lateral, não de um manifesto
 * gerado: a barra já é derivada do conteúdo real pelo Docusaurus, e um arquivo
 * gerado seria uma segunda fonte de verdade a dessincronizar.
 *
 * A seção é identificada por **prefixo de URL**, não por categoria da barra.
 * `sidebars.ts` agrupa por nível do percurso e usa `autogenerated`, que achata
 * o conteúdo do diretório dentro da categoria do nível — não existe uma
 * categoria por seção para consultar. O prefixo (`/distributed-systems/`) é o
 * que de fato delimita uma seção.
 */

import React from 'react';
import Translate, {translate} from '@docusaurus/Translate';
import {useDoc, useDocsSidebar} from '@docusaurus/plugin-content-docs/client';
import type {PropSidebarItem} from '@docusaurus/plugin-content-docs';
import {setManyRead} from '@site/src/lib/readingProgress';
import {useReadCount} from './useReadingProgress';
import styles from './styles.module.css';

/** `docId` de todo link da barra cuja URL cai sob `prefix`, exceto o próprio índice. */
function docIdsUnder(items: readonly PropSidebarItem[], prefix: string, out: string[] = []): string[] {
  for (const item of items) {
    if (item.type === 'link') {
      if (item.docId && item.href.startsWith(prefix) && item.href !== prefix) {
        out.push(item.docId);
      }
    } else if (item.type === 'category') {
      docIdsUnder(item.items, prefix, out);
    }
  }
  return out;
}

export default function SectionProgress(): React.ReactElement | null {
  const sidebar = useDocsSidebar();
  const {metadata} = useDoc();

  // O índice pode ser servido com ou sem barra final conforme `trailingSlash`;
  // o prefixo precisa da barra para não casar com uma seção de nome parecido.
  const prefix = metadata.permalink.endsWith('/') ? metadata.permalink : `${metadata.permalink}/`;

  const ids = React.useMemo(
    () => (sidebar ? docIdsUnder(sidebar.items, prefix) : []),
    [sidebar, prefix],
  );

  const done = useReadCount(ids);

  // Seção ainda sem tópicos escritos não tem progresso a mostrar.
  if (ids.length === 0) return null;

  const pct = Math.round((done / ids.length) * 100);
  const allRead = done === ids.length;

  return (
    <section
      className={styles.summary}
      aria-label={translate({
        id: 'readingProgress.section.label',
        message: 'Progresso de leitura desta seção',
        description: 'Rótulo acessível do bloco de progresso da seção',
      })}>
      <div className={styles.summaryHead}>
        <span className={styles.summaryLabel}>
          <Translate
            id="readingProgress.section.title"
            description="Título do bloco de progresso da seção">
            Seu progresso nesta seção
          </Translate>
        </span>
        <span className={styles.summaryCount}>
          {done} / {ids.length} · {pct}%
        </span>
      </div>

      <div
        className={styles.track}
        role="progressbar"
        aria-valuenow={done}
        aria-valuemin={0}
        aria-valuemax={ids.length}>
        <div className={styles.fill} style={{width: `${pct}%`}} />
      </div>

      <div className={styles.actions}>
        <button type="button" className={styles.action} onClick={() => setManyRead(ids, !allRead)}>
          {allRead ? (
            <Translate
              id="readingProgress.section.unmarkAll"
              description="Botão para desmarcar todos os documentos da seção">
              Desmarcar todos
            </Translate>
          ) : (
            <Translate
              id="readingProgress.section.markAll"
              description="Botão para marcar todos os documentos da seção como lidos">
              Marcar todos como lidos
            </Translate>
          )}
        </button>
      </div>
    </section>
  );
}
