import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * F0: sidebar autogerada a partir da estrutura de diretórios, ordenada por
 * `sidebar_position` no front matter de cada documento.
 *
 * F1 substitui isto por um agrupamento explícito nos sete níveis do percurso
 * (ver SPEC.md §4.1), porque a ordem de leitura entre seções não é derivável
 * da árvore de diretórios: o Nível 05 abrange onze seções não contíguas.
 */
const sidebars: SidebarsConfig = {
  curriculum: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
