import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Navegação agrupada pelos sete níveis do percurso (SPEC.md §4.1).
 *
 * A ordem de leitura entre seções não é derivável da árvore de diretórios: o
 * Nível 05 abrange onze seções não contíguas (07–14, 17, 18, 20), e as seções
 * 21 e 22 são transversais, não pertencendo a nível nenhum. Por isso o
 * agrupamento é explícito aqui e o conteúdo de cada seção é autogerado,
 * ordenado por `sidebar_position`.
 */

const level = (label: string, dirs: string[], collapsed = true) => ({
  type: 'category' as const,
  label,
  collapsed,
  items: dirs.map((dirName) => ({type: 'autogenerated' as const, dirName})),
});

/** Nível 05 tem seções demais para uma lista plana; cada uma vira subgrupo. */
const architectureLevel = {
  type: 'category' as const,
  label: 'Nível 05 — Arquitetura',
  collapsed: true,
  items: [
    {type: 'category' as const, label: 'Dados', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '07-data-architecture'}]},
    {type: 'category' as const, label: 'Integração', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '08-integration-architecture'}]},
    {type: 'category' as const, label: 'Nuvem', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '09-cloud-architecture'}]},
    {type: 'category' as const, label: 'Segurança', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '10-security'}]},
    {type: 'category' as const, label: 'Escalabilidade', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '11-scalability'}]},
    {type: 'category' as const, label: 'Confiabilidade', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '12-reliability'}]},
    {type: 'category' as const, label: 'Observabilidade', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '13-observability'}]},
    {type: 'category' as const, label: 'DevOps e Plataforma', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '14-devops-and-platform'}]},
    {type: 'category' as const, label: 'Documentação', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '17-architecture-documentation'}]},
    {type: 'category' as const, label: 'Decisões', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '18-architecture-decisions'}]},
    {type: 'category' as const, label: 'Trade-offs', collapsed: true,
      items: [{type: 'autogenerated' as const, dirName: '20-trade-offs'}]},
  ],
};

const sidebars: SidebarsConfig = {
  curriculum: [
    'intro',
    'how-to-use',
    'maturity-model',

    level('Nível 01 — Fundamentos', ['01-fundamentals'], false),
    level('Nível 02 — Design de Software', [
      '02-software-design',
      '03-design-patterns',
      '04-domain-driven-design',
    ]),
    level('Nível 03 — Design de Sistemas', ['05-system-design']),
    level('Nível 04 — Sistemas Distribuídos', ['06-distributed-systems']),
    architectureLevel,
    level('Nível 06 — Arquitetura Corporativa', [
      '15-enterprise-architecture',
      '16-legacy-modernization',
      '19-architecture-governance',
    ]),
    level('Nível 07 — Liderança em Arquitetura', ['23-architecture-leadership']),

    // Transversais: aplicação e avaliação, não pertencem a um nível.
    level('Aplicação', ['21-case-studies', '22-system-design-interviews']),

    {
      type: 'category',
      label: 'Referência',
      collapsed: true,
      items: ['glossary', 'i18n-terminology'],
    },
  ],
};

export default sidebars;
